=== zbbsdsb/cebu/cebu_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "command_history": {
      "type": "object"
    },
    "equivalence_classes": {
      "type": "array"
    },
    "format": {
      "const": "cebu",
      "type": "string"
    },
    "format_version": {
      "type": "integer"
    },
    "labels": {
      "type": "object"
    },
    "simplices": {
      "items": {
        "properties": {
          "dimension": {
            "type": "integer"
          },
          "id": {
            "type": "integer"
          },
          "vertices": {
            "items": {
              "type": "integer"
            },
            "type": "array"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "statistics": {
      "properties": {
        "edge_count": {
          "type": "integer"
        },
        "face_count": {
          "type": "integer"
        },
        "max_dimension": {
          "type": "integer"
        },
        "simplex_count": {
          "type": "integer"
        },
        "vertex_count": {
          "type": "integer"
        }
      },
      "type": "object"
    },
    "version": {
      "type": "string"
    }
  },
  "required": [
    "format",
    "version",
    "simplices"
  ],
  "type": "object"
}

=== zbbsdsb/cebu/test_basic_complex.json
{
  "format": "cebu",
  "format_version": 1,
  "simplices": [
    {
      "dimension": 0,
      "id": 0,
      "vertices": [
        0
      ]
    },
    {
      "dimension": 0,
      "id": 1,
      "vertices": [
        1
      ]
    },
    {
      "dimension": 0,
      "id": 2,
      "vertices": [
        2
      ]
    },
    {
      "dimension": 1,
      "id": 3,
      "vertices": [
        0,
        1
      ]
    },
    {
      "dimension": 1,
      "id": 4,
      "vertices": [
        1,
        2
      ]
    },
    {
      "dimension": 1,
      "id": 5,
      "vertices": [
        0,
        2
      ]
    },
    {
      "dimension": 2,
      "id": 6,
      "vertices": [
        0,
        1,
        2
      ]
    }
  ],
  "statistics": {
    "simplex_count": 7,
    "vertex_count": 3
  },
  "version": "0.7.1"
}
